services:
  postgres:
    container_name: postgres
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dragonfruitnet
      POSTGRES_DB: dragonfruit
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: {}
