// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v5.29.2
// source: oniondb.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "";

export interface OnionDb {
  /** Magic Bytes. Should always be 0xDB followed by the version number */
  magicBytes: Uint8Array;
  /** Database version number. Higher value means newer database (usually a UNIX Epoch) */
  dbVersion: number;
  /** Version of the Tor Onionoo dataset used to build the database. Takes the form of a UNIX Epoch. */
  torDirVersion: number;
  /** Version of the IPFire location.db file used to build the address ranges. If provided, is a UNIX Epoch otherwise all v*_range fields will be empty. */
  geoDirVersion?:
    | number
    | undefined;
  /** Onionoo Dataset license expression. If null no license data was provided/could be found. */
  torLicense?:
    | string
    | undefined;
  /** location.db Dataset license expression. If null no license data was provided/could be found. */
  geoLicense?: string | undefined;
  countries: OnionDbCountry[];
}

export interface OnionDbCountry {
  countryCode: string;
  countryName: string;
  countryNameLocal: string;
  totalNodeCount: number;
  entryNodeCount: number;
  exitNodeCount: number;
  fastNodeCount: number;
  onlineNodeCount: number;
  v4Ranges: AddressRange[];
  v6Ranges: AddressRange[];
}

export interface AddressRange {
  start: Uint8Array;
  end: Uint8Array;
}

function createBaseOnionDb(): OnionDb {
  return {
    magicBytes: new Uint8Array(0),
    dbVersion: 0,
    torDirVersion: 0,
    geoDirVersion: undefined,
    torLicense: undefined,
    geoLicense: undefined,
    countries: [],
  };
}

export const OnionDb: MessageFns<OnionDb> = {
  encode(message: OnionDb, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.magicBytes.length !== 0) {
      writer.uint32(10).bytes(message.magicBytes);
    }
    if (message.dbVersion !== 0) {
      writer.uint32(16).int64(message.dbVersion);
    }
    if (message.torDirVersion !== 0) {
      writer.uint32(24).int64(message.torDirVersion);
    }
    if (message.geoDirVersion !== undefined) {
      writer.uint32(32).int64(message.geoDirVersion);
    }
    if (message.torLicense !== undefined) {
      writer.uint32(42).string(message.torLicense);
    }
    if (message.geoLicense !== undefined) {
      writer.uint32(50).string(message.geoLicense);
    }
    for (const v of message.countries) {
      OnionDbCountry.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnionDb {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnionDb();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.magicBytes = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.dbVersion = longToNumber(reader.int64());
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.torDirVersion = longToNumber(reader.int64());
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.geoDirVersion = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.torLicense = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.geoLicense = reader.string();
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.countries.push(OnionDbCountry.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnionDb {
    return {
      magicBytes: isSet(object.magicBytes) ? bytesFromBase64(object.magicBytes) : new Uint8Array(0),
      dbVersion: isSet(object.dbVersion) ? globalThis.Number(object.dbVersion) : 0,
      torDirVersion: isSet(object.torDirVersion) ? globalThis.Number(object.torDirVersion) : 0,
      geoDirVersion: isSet(object.geoDirVersion) ? globalThis.Number(object.geoDirVersion) : undefined,
      torLicense: isSet(object.torLicense) ? globalThis.String(object.torLicense) : undefined,
      geoLicense: isSet(object.geoLicense) ? globalThis.String(object.geoLicense) : undefined,
      countries: globalThis.Array.isArray(object?.countries)
        ? object.countries.map((e: any) => OnionDbCountry.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OnionDb): unknown {
    const obj: any = {};
    if (message.magicBytes.length !== 0) {
      obj.magicBytes = base64FromBytes(message.magicBytes);
    }
    if (message.dbVersion !== 0) {
      obj.dbVersion = Math.round(message.dbVersion);
    }
    if (message.torDirVersion !== 0) {
      obj.torDirVersion = Math.round(message.torDirVersion);
    }
    if (message.geoDirVersion !== undefined) {
      obj.geoDirVersion = Math.round(message.geoDirVersion);
    }
    if (message.torLicense !== undefined) {
      obj.torLicense = message.torLicense;
    }
    if (message.geoLicense !== undefined) {
      obj.geoLicense = message.geoLicense;
    }
    if (message.countries?.length) {
      obj.countries = message.countries.map((e) => OnionDbCountry.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OnionDb>, I>>(base?: I): OnionDb {
    return OnionDb.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OnionDb>, I>>(object: I): OnionDb {
    const message = createBaseOnionDb();
    message.magicBytes = object.magicBytes ?? new Uint8Array(0);
    message.dbVersion = object.dbVersion ?? 0;
    message.torDirVersion = object.torDirVersion ?? 0;
    message.geoDirVersion = object.geoDirVersion ?? undefined;
    message.torLicense = object.torLicense ?? undefined;
    message.geoLicense = object.geoLicense ?? undefined;
    message.countries = object.countries?.map((e) => OnionDbCountry.fromPartial(e)) || [];
    return message;
  },
};

function createBaseOnionDbCountry(): OnionDbCountry {
  return {
    countryCode: "",
    countryName: "",
    countryNameLocal: "",
    totalNodeCount: 0,
    entryNodeCount: 0,
    exitNodeCount: 0,
    fastNodeCount: 0,
    onlineNodeCount: 0,
    v4Ranges: [],
    v6Ranges: [],
  };
}

export const OnionDbCountry: MessageFns<OnionDbCountry> = {
  encode(message: OnionDbCountry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.countryCode !== "") {
      writer.uint32(10).string(message.countryCode);
    }
    if (message.countryName !== "") {
      writer.uint32(18).string(message.countryName);
    }
    if (message.countryNameLocal !== "") {
      writer.uint32(26).string(message.countryNameLocal);
    }
    if (message.totalNodeCount !== 0) {
      writer.uint32(32).uint32(message.totalNodeCount);
    }
    if (message.entryNodeCount !== 0) {
      writer.uint32(40).uint32(message.entryNodeCount);
    }
    if (message.exitNodeCount !== 0) {
      writer.uint32(48).uint32(message.exitNodeCount);
    }
    if (message.fastNodeCount !== 0) {
      writer.uint32(56).uint32(message.fastNodeCount);
    }
    if (message.onlineNodeCount !== 0) {
      writer.uint32(64).uint32(message.onlineNodeCount);
    }
    for (const v of message.v4Ranges) {
      AddressRange.encode(v!, writer.uint32(74).fork()).join();
    }
    for (const v of message.v6Ranges) {
      AddressRange.encode(v!, writer.uint32(82).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): OnionDbCountry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseOnionDbCountry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.countryCode = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.countryName = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.countryNameLocal = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.totalNodeCount = reader.uint32();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.entryNodeCount = reader.uint32();
          continue;
        }
        case 6: {
          if (tag !== 48) {
            break;
          }

          message.exitNodeCount = reader.uint32();
          continue;
        }
        case 7: {
          if (tag !== 56) {
            break;
          }

          message.fastNodeCount = reader.uint32();
          continue;
        }
        case 8: {
          if (tag !== 64) {
            break;
          }

          message.onlineNodeCount = reader.uint32();
          continue;
        }
        case 9: {
          if (tag !== 74) {
            break;
          }

          message.v4Ranges.push(AddressRange.decode(reader, reader.uint32()));
          continue;
        }
        case 10: {
          if (tag !== 82) {
            break;
          }

          message.v6Ranges.push(AddressRange.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): OnionDbCountry {
    return {
      countryCode: isSet(object.countryCode) ? globalThis.String(object.countryCode) : "",
      countryName: isSet(object.countryName) ? globalThis.String(object.countryName) : "",
      countryNameLocal: isSet(object.countryNameLocal) ? globalThis.String(object.countryNameLocal) : "",
      totalNodeCount: isSet(object.totalNodeCount) ? globalThis.Number(object.totalNodeCount) : 0,
      entryNodeCount: isSet(object.entryNodeCount) ? globalThis.Number(object.entryNodeCount) : 0,
      exitNodeCount: isSet(object.exitNodeCount) ? globalThis.Number(object.exitNodeCount) : 0,
      fastNodeCount: isSet(object.fastNodeCount) ? globalThis.Number(object.fastNodeCount) : 0,
      onlineNodeCount: isSet(object.onlineNodeCount) ? globalThis.Number(object.onlineNodeCount) : 0,
      v4Ranges: globalThis.Array.isArray(object?.v4Ranges)
        ? object.v4Ranges.map((e: any) => AddressRange.fromJSON(e))
        : [],
      v6Ranges: globalThis.Array.isArray(object?.v6Ranges)
        ? object.v6Ranges.map((e: any) => AddressRange.fromJSON(e))
        : [],
    };
  },

  toJSON(message: OnionDbCountry): unknown {
    const obj: any = {};
    if (message.countryCode !== "") {
      obj.countryCode = message.countryCode;
    }
    if (message.countryName !== "") {
      obj.countryName = message.countryName;
    }
    if (message.countryNameLocal !== "") {
      obj.countryNameLocal = message.countryNameLocal;
    }
    if (message.totalNodeCount !== 0) {
      obj.totalNodeCount = Math.round(message.totalNodeCount);
    }
    if (message.entryNodeCount !== 0) {
      obj.entryNodeCount = Math.round(message.entryNodeCount);
    }
    if (message.exitNodeCount !== 0) {
      obj.exitNodeCount = Math.round(message.exitNodeCount);
    }
    if (message.fastNodeCount !== 0) {
      obj.fastNodeCount = Math.round(message.fastNodeCount);
    }
    if (message.onlineNodeCount !== 0) {
      obj.onlineNodeCount = Math.round(message.onlineNodeCount);
    }
    if (message.v4Ranges?.length) {
      obj.v4Ranges = message.v4Ranges.map((e) => AddressRange.toJSON(e));
    }
    if (message.v6Ranges?.length) {
      obj.v6Ranges = message.v6Ranges.map((e) => AddressRange.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<OnionDbCountry>, I>>(base?: I): OnionDbCountry {
    return OnionDbCountry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<OnionDbCountry>, I>>(object: I): OnionDbCountry {
    const message = createBaseOnionDbCountry();
    message.countryCode = object.countryCode ?? "";
    message.countryName = object.countryName ?? "";
    message.countryNameLocal = object.countryNameLocal ?? "";
    message.totalNodeCount = object.totalNodeCount ?? 0;
    message.entryNodeCount = object.entryNodeCount ?? 0;
    message.exitNodeCount = object.exitNodeCount ?? 0;
    message.fastNodeCount = object.fastNodeCount ?? 0;
    message.onlineNodeCount = object.onlineNodeCount ?? 0;
    message.v4Ranges = object.v4Ranges?.map((e) => AddressRange.fromPartial(e)) || [];
    message.v6Ranges = object.v6Ranges?.map((e) => AddressRange.fromPartial(e)) || [];
    return message;
  },
};

function createBaseAddressRange(): AddressRange {
  return { start: new Uint8Array(0), end: new Uint8Array(0) };
}

export const AddressRange: MessageFns<AddressRange> = {
  encode(message: AddressRange, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.start.length !== 0) {
      writer.uint32(10).bytes(message.start);
    }
    if (message.end.length !== 0) {
      writer.uint32(18).bytes(message.end);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AddressRange {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAddressRange();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.start = reader.bytes();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.end = reader.bytes();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AddressRange {
    return {
      start: isSet(object.start) ? bytesFromBase64(object.start) : new Uint8Array(0),
      end: isSet(object.end) ? bytesFromBase64(object.end) : new Uint8Array(0),
    };
  },

  toJSON(message: AddressRange): unknown {
    const obj: any = {};
    if (message.start.length !== 0) {
      obj.start = base64FromBytes(message.start);
    }
    if (message.end.length !== 0) {
      obj.end = base64FromBytes(message.end);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AddressRange>, I>>(base?: I): AddressRange {
    return AddressRange.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AddressRange>, I>>(object: I): AddressRange {
    const message = createBaseAddressRange();
    message.start = object.start ?? new Uint8Array(0);
    message.end = object.end ?? new Uint8Array(0);
    return message;
  },
};

function bytesFromBase64(b64: string): Uint8Array {
  if ((globalThis as any).Buffer) {
    return Uint8Array.from(globalThis.Buffer.from(b64, "base64"));
  } else {
    const bin = globalThis.atob(b64);
    const arr = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; ++i) {
      arr[i] = bin.charCodeAt(i);
    }
    return arr;
  }
}

function base64FromBytes(arr: Uint8Array): string {
  if ((globalThis as any).Buffer) {
    return globalThis.Buffer.from(arr).toString("base64");
  } else {
    const bin: string[] = [];
    arr.forEach((byte) => {
      bin.push(globalThis.String.fromCharCode(byte));
    });
    return globalThis.btoa(bin.join(""));
  }
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
